// Type definitions
export interface Tool {
  id: string;
  name: string;
  description: string;
  shortDesc: string;
  url: string;
  category: string;
  tags: string[];
  pricing: 'free' | 'freemium' | 'paid';
  useCases: string[];
  prosCons: { pros: string[]; cons: string[] };
  officialUrl: string;
  featured?: boolean;
  score?: number;
}

export interface Category {
  id: string;
  name: string;
  icon: string;
  count: number;
}

export const categories: Category[] = [
  { id: 'writing', name: 'AI Writing', icon: '\u270d\ufe0f', count: 0 },
  { id: 'image', name: 'AI Image', icon: '\ud83c\udfa8', count: 0 },
  { id: 'code', name: 'AI Coding', icon: '\ud83d\udcbb', count: 0 },
  { id: 'video', name: 'AI Video', icon: '\ud83c\udfac', count: 0 },
  { id: 'marketing', name: 'AI Marketing', icon: '\ud83d\udce2', count: 0 },
  { id: 'audio', name: 'AI Audio', icon: '\ud83c\udfb5', count: 0 },
  { id: 'productivity', name: 'AI Productivity', icon: '\u26a1', count: 0 },
  { id: 'search', name: 'AI Search', icon: '\ud83d\udd0d', count: 0 },
];

export function seoTitle(t: Tool): string {
  return t.name + ' Review 2026: Features, Pricing, Pros & Cons | STYK Ai';
}
export function seoDescription(t: Tool): string {
  return 'Review of ' + t.name + ': ' + t.shortDesc + '. Learn about features, pricing, use cases, pros & cons. Rating ' + (t.score || 'N/A') + '/10.';
}

export const tools: Tool[] = [
  {
    id: 'chatgpt',
    name: 'ChatGPT',
    description: 'OpenAI 开发的对话式 AI 助手，支持文本生成、代码编写、数据分析、图片理解等。GPT-4o 具备多模态能力，广泛应用于内容创作、编程辅助、学习研究等领域。',
    shortDesc: '领先的对话式 AI 助手，支持多模态交互',
    url: 'https://chat.openai.com',
    category: 'writing',
    tags: ['AI 对话', '内容生成', '代码辅助', '多模态', 'GPT-4o'],
    pricing: 'freemium',
    useCases: ['内容创作', '编程辅助', '学习研究', '数据分析', '头脑风暴'],
    prosCons: { pros: ['多模态理解', '自然对话', '生态丰富', '插件系统', '持续更新'], cons: ['免费版有限制', '有时不准确', '无实时数据', '隐私考虑', '付费较高'] },
    officialUrl: 'https://chat.openai.com',
    score: 9.5,
  },
  {
    id: 'claude',
    name: 'Claude',
    description: 'Anthropic 开发的 AI 助手，擅长长文本处理、深度分析和对话。Claude 4 具备 200K token 上下文窗口。强调安全性和诚实回复。',
    shortDesc: '长文本处理专家，安全可靠的 AI 助手',
    url: 'https://claude.ai',
    category: 'writing',
    tags: ['AI 对话', '长文本', '代码生成', '安全 AI', '分析'],
    pricing: 'freemium',
    useCases: ['长文档分析', '代码编写', '学术写作', '战略分析', '内容创作'],
    prosCons: { pros: ['超长上下文', '深度分析', '安全可靠', '编程出色', '详细回复'], cons: ['不支持图像', '中文稍弱', '无实时搜索', '输出限制', '付费版较贵'] },
    officialUrl: 'https://claude.ai',
    score: 9.4,
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    description: '深度求索开发的 AI 模型，在编程、数学推理方面表现突出。DeepSeek-R1 具备强大推理能力，支持长上下文。',
    shortDesc: '推理能力突出的国产 AI 模型',
    url: 'https://chat.deepseek.com',
    category: 'code',
    tags: ['AI 编程', '数学推理', '开源 AI', '国产', 'API'],
    pricing: 'freemium',
    useCases: ['编程辅助', '数学解题', '逻辑推理', '代码审查', 'API 集成'],
    prosCons: { pros: ['推理能力强', '编程优秀', '性价比高', '开源部分', '中文支持好'], cons: ['生态较小', '多模态有限', '知名度较低', '稳定性待提升', '文档较少'] },
    officialUrl: 'https://chat.deepseek.com',
    score: 9,
  },
  {
    id: 'github-copilot',
    name: 'GitHub Copilot',
    description: 'GitHub 推出的 AI 编程助手，基于 OpenAI Codex。支持 2000+ 种语言，无缝集成 VS Code、JetBrains 等主流 IDE。',
    shortDesc: '最流行的 AI 编程助手',
    url: 'https://github.com/features/copilot',
    category: 'code',
    tags: ['AI 编程', '代码补全', 'VS Code', 'GitHub', 'IDE 插件'],
    pricing: 'paid',
    useCases: ['日常编程', '代码补全', '测试编写', '代码审查', '学习新语言'],
    prosCons: { pros: ['多 IDE 支持', '上下文理解', '代码质量高', '团队协作', '持续更新'], cons: ['付费较高', '需要网络', '隐私顾虑', '有时不准', '小语种差'] },
    officialUrl: 'https://github.com/features/copilot',
    score: 9.3,
  },
  {
    id: 'cursor',
    name: 'Cursor',
    description: '基于 AI 的代码编辑器，底层使用 VS Code 架构。深度集成 Claude 和 GPT 模型，支持行内代码编辑、多文件重构。',
    shortDesc: 'AI 原生代码编辑器',
    url: 'https://cursor.sh',
    category: 'code',
    tags: ['AI 编辑器', '代码重构', 'VS Code', 'AI 编程', '开发工具'],
    pricing: 'freemium',
    useCases: ['AI 驱动编程', '代码重构', '多文件编辑', 'Bug 修复', '项目搭建'],
    prosCons: { pros: ['多模型支持', 'Composer 模式', '多文件编辑', '上下文感知', '迭代快速'], cons: ['免费版有限', '分支竞争', '依赖网络', '隐私问题', '学习成本'] },
    officialUrl: 'https://cursor.sh',
    score: 9.2,
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    description: 'AI 搜索引擎，实时联网并提供带引用来源的答案。Pro 版支持 GPT-4、Claude 等模型切换。',
    shortDesc: '带引用来源的 AI 搜索引擎',
    url: 'https://perplexity.ai',
    category: 'search',
    tags: ['AI 搜索', '实时搜索', '学术研究', '引用来源', '知识查询'],
    pricing: 'freemium',
    useCases: ['研究查询', '学术搜索', '事实核查', '学习辅助', '信息聚合'],
    prosCons: { pros: ['实时联网', '引用来源', '多模型支持', '搜索准确', '界面简洁'], cons: ['Pro 版贵', '免费版有限', '中文略差', '有时幻觉', '收藏功能弱'] },
    officialUrl: 'https://perplexity.ai',
    score: 9,
  },
  {
    id: 'midjourney',
    name: 'Midjourney',
    description: '顶尖的 AI 图像生成工具，艺术风格和细节表现著称。通过 Discord 使用，V6 模型在真实感上达到新高度。',
    shortDesc: '顶尖 AI 图像生成，艺术风格出众',
    url: 'https://www.midjourney.com',
    category: 'image',
    tags: ['AI 绘图', '艺术创作', 'Discord', '生成艺术', 'AI 设计'],
    pricing: 'paid',
    useCases: ['艺术创作', '概念设计', '广告素材', '游戏原画', '品牌视觉'],
    prosCons: { pros: ['艺术感强', '细节丰富', '社区活跃', '持续更新', '风格多样'], cons: ['需 Discord', '付费较贵', '无免费版', '控制较少', '不适合文字'] },
    officialUrl: 'https://www.midjourney.com',
    score: 9.4,
  },
  {
    id: 'dalle-3',
    name: 'DALL-E 3',
    description: 'OpenAI 的图像生成模型，集成在 ChatGPT 中。文本理解能力强，可以精确生成描述中的内容。',
    shortDesc: 'ChatGPT 内置的高质量 AI 图像生成',
    url: 'https://openai.com/dall-e-3',
    category: 'image',
    tags: ['AI 绘图', 'ChatGPT', '文生图', '图像编辑', 'OpenAI'],
    pricing: 'paid',
    useCases: ['创意设计', '内容配图', '广告设计', '概念可视化', '社交媒体'],
    prosCons: { pros: ['文本理解准确', 'ChatGPT 集成', '安全机制', '编辑功能', '质量稳定'], cons: ['付费使用', '风格较单一', '分辨率限制', '无独立平台', '生成较慢'] },
    officialUrl: 'https://openai.com/dall-e-3',
    score: 9.1,
  },
  {
    id: 'stable-diffusion-3',
    name: 'Stable Diffusion 3',
    description: 'Stability AI 的开源图像生成模型。支持本地部署，完全免费。SD3 在文字渲染和多主体理解上有重大提升。',
    shortDesc: '开源免费的 AI 图像生成模型',
    url: 'https://stability.ai',
    category: 'image',
    tags: ['开源', '本地部署', 'AI 绘图', '免费', 'Stable Diffusion'],
    pricing: 'free',
    useCases: ['本地创作', '商业应用', '模型定制', '科研实验', '批量生成'],
    prosCons: { pros: ['完全免费', '本地运行', '开源可定制', '社区丰富', 'LoRA 支持'], cons: ['需要 GPU', '安装复杂', '默认效果一般', '模型需调优', '硬件要求高'] },
    officialUrl: 'https://stability.ai',
    score: 9,
  },
  {
    id: 'leonardo',
    name: 'Leonardo AI',
    description: '一站式 AI 创作平台，集成图像生成、视频生成和 3D 纹理。每日免费额度充足，适合游戏资产创作。',
    shortDesc: '一站式 AI 创作平台',
    url: 'https://leonardo.ai',
    category: 'image',
    tags: ['AI 创作', '图像生成', '3D 纹理', '游戏资产', '视频生成'],
    pricing: 'freemium',
    useCases: ['游戏设计', '概念艺术', '角色设计', '环境设计', '视频素材'],
    prosCons: { pros: ['功能全面', '免费额度多', '社区交流', '训练模型', '实时生成'], cons: ['免费有水印', '付费订阅', '生成速度慢', '细节一般', '无独立应用'] },
    officialUrl: 'https://leonardo.ai',
    score: 8.8,
  },
  {
    id: 'canva-ai',
    name: 'Canva AI',
    description: '在线设计平台集成 AI 功能，支持 AI 图像生成、背景移除、魔法编辑。海量模板，适合社交媒体设计。',
    shortDesc: 'AI 赋能的在线设计平台',
    url: 'https://www.canva.com',
    category: 'image',
    tags: ['在线设计', 'AI 编辑', '模板', '社交媒体', '平面设计'],
    pricing: 'freemium',
    useCases: ['社交媒体设计', '演示文稿', '营销素材', '视频编辑', '品牌设计'],
    prosCons: { pros: ['操作简单', '模板丰富', '团队协作', 'AI 功能强', '多平台'], cons: ['免费功能有限', '部分 AI 需付费', '输出质量一般', '商业授权需注意', '高级功能贵'] },
    officialUrl: 'https://www.canva.com',
    score: 9.1,
  },
  {
    id: 'grammarly-ai',
    name: 'Grammarly AI',
    description: 'AI 写作助手，提供语法检查、拼写纠正、语气调整、风格优化。支持浏览器插件、桌面应用和移动端。',
    shortDesc: 'AI 写作辅助工具',
    url: 'https://grammarly.com',
    category: 'writing',
    tags: ['语法检查', '写作辅助', '英语纠错', '语气调整', '浏览器插件'],
    pricing: 'freemium',
    useCases: ['英文写作', '邮件优化', '学术写作', '商务沟通', '内容校对'],
    prosCons: { pros: ['实时纠错', '多平台支持', '准确性高', '语气建议', '企业方案'], cons: ['免费功能有限', '主要英文', '隐私顾虑', '有时过严', '高级版贵'] },
    officialUrl: 'https://grammarly.com',
    score: 8.9,
  },
  {
    id: 'notion-ai',
    name: 'Notion AI',
    description: 'Notion 的内置 AI 助手，支持写作辅助、内容总结、翻译、项目管理。深度集成知识库和协作功能。',
    shortDesc: 'Notion 内置的 AI 工作助手',
    url: 'https://www.notion.so/product/ai',
    category: 'writing',
    tags: ['笔记', '知识管理', '写作辅助', '项目管理', '协作'],
    pricing: 'paid',
    useCases: ['项目文档', '会议记录', '知识库', '团队协作', '写作辅助'],
    prosCons: { pros: ['无缝集成', '功能多样', '翻译总结', '会议助手', '知识管理'], cons: ['额外付费', 'AI 功能收费', '离线差', '复杂表格弱', '中文支持一般'] },
    officialUrl: 'https://www.notion.so/product/ai',
    score: 8.8,
  },
  {
    id: 'jasper',
    name: 'Jasper',
    description: '专业 AI 内容创作平台，专为营销团队设计。品牌语调控制、SEO 优化、多渠道内容生成。',
    shortDesc: '专业 AI 内容创作与营销平台',
    url: 'https://www.jasper.ai',
    category: 'writing',
    tags: ['内容创作', '营销文案', '品牌语调', 'SEO 写作', '团队协作'],
    pricing: 'paid',
    useCases: ['营销文案', '广告投放', 'SEO 内容', '社媒管理', '品牌内容'],
    prosCons: { pros: ['品牌语气一致', 'SEO 集成', '模板丰富', '团队协作', '质量稳定'], cons: ['价格较高', '无免费版', '过度营销感', '英文为主', '学习曲线'] },
    officialUrl: 'https://www.jasper.ai',
    score: 8.7,
  },
  {
    id: 'writesonic',
    name: 'Writesonic',
    description: '多功能 AI 写作平台，支持文章生成、广告文案、SEO 内容。内置 Chatsonic 对话式 AI 助手。',
    shortDesc: '多功能 AI 写作与内容生成平台',
    url: 'https://writesonic.com',
    category: 'writing',
    tags: ['写作辅助', '内容生成', 'SEO 工具', 'AI 对话', 'API'],
    pricing: 'freemium',
    useCases: ['文章写作', '广告文案', '产品描述', '社媒内容', '邮件营销'],
    prosCons: { pros: ['免费额度', '功能全面', 'Chatsonic 集成', 'SEO 优化', 'API 支持'], cons: ['生成质量不一', '需要编辑', '免费有限', 'AI 味重', '付费较贵'] },
    officialUrl: 'https://writesonic.com',
    score: 8.5,
  },
  {
    id: 'copy-ai',
    name: 'Copy.ai',
    description: 'AI 营销文案生成工具，专为电商和 SaaS 公司设计。支持产品描述、社媒文案、邮件营销。',
    shortDesc: 'AI 营销文案自动生成',
    url: 'https://www.copy.ai',
    category: 'marketing',
    tags: ['营销文案', '电商工具', '自动化', '邮件营销', 'SaaS'],
    pricing: 'freemium',
    useCases: ['产品描述', '社媒营销', '邮件文案', '广告创意', '品牌文案'],
    prosCons: { pros: ['易于使用', 'Workflow 强大', '种类多样', '多语言', '免费版可用'], cons: ['质量不一致', '需人工编辑', '深度不足', '品牌语调弱', '复杂场景弱'] },
    officialUrl: 'https://www.copy.ai',
    score: 8.5,
  },
  {
    id: 'runway',
    name: 'Runway',
    description: 'AI 视频生成与编辑平台。Gen-4 Alpha 可生成高质量视频，支持文生视频、图生视频。',
    shortDesc: 'AI 视频生成与专业编辑平台',
    url: 'https://runwayml.com',
    category: 'video',
    tags: ['AI 视频', '视频生成', '视频编辑', 'Gen-4', '创意工具'],
    pricing: 'freemium',
    useCases: ['视频生成', '特效制作', '绿幕抠像', '广告短片', '创意实验'],
    prosCons: { pros: ['视频质量高', '功能全面', '持续更新', 'Gen-4 强大', '专业编辑'], cons: ['付费较贵', '免费有限', '生成时间长', '一致性差', '高级功能贵'] },
    officialUrl: 'https://runwayml.com',
    score: 9,
  },
  {
    id: 'synthesia',
    name: 'Synthesia',
    description: 'AI 数字人视频生成平台。150+ AI 虚拟形象，支持 120+ 语言。输入文本即可生成真人演讲视频。',
    shortDesc: 'AI 数字人视频生成平台',
    url: 'https://www.synthesia.io',
    category: 'video',
    tags: ['AI 数字人', '视频制作', '培训视频', '企业工具', '多语言'],
    pricing: 'paid',
    useCases: ['企业培训', '营销视频', '产品说明', '内部沟通', '多语言内容'],
    prosCons: { pros: ['逼真数字人', '多语言支持', '无需拍摄', '模板丰富', '企业安全'], cons: ['价格较高', '无免费版', '表情有限', '手势不自然', '定制化弱'] },
    officialUrl: 'https://www.synthesia.io',
    score: 8.9,
  },
  {
    id: 'elevenlabs',
    name: 'ElevenLabs',
    description: '最先进的 AI 语音合成平台。语音克隆、多语言 TTS、有声书生成。支持情感控制和语速调整。',
    shortDesc: '最先进的 AI 语音合成平台',
    url: 'https://elevenlabs.io',
    category: 'audio',
    tags: ['AI 语音', '语音克隆', 'TTS', '有声书', '配音'],
    pricing: 'freemium',
    useCases: ['有声书制作', '视频配音', '语音助手', '播客创作', '游戏角色配音'],
    prosCons: { pros: ['音质极高', '情感丰富', '语音克隆准确', '多语言', 'API 完善'], cons: ['免费有限', '付费较贵', '长文本贵', '中文可改进', '计算资源高'] },
    officialUrl: 'https://elevenlabs.io',
    score: 9.3,
  },
  {
    id: 'suno',
    name: 'Suno',
    description: 'AI 音乐生成平台，根据文本提示生成完整歌曲。支持多种音乐风格，V4 模型可生成带人声的高质量音乐。',
    shortDesc: 'AI 音乐生成，文本秒变歌曲',
    url: 'https://suno.ai',
    category: 'audio',
    tags: ['AI 音乐', '音乐生成', '歌曲创作', 'AI 作曲', '创意工具'],
    pricing: 'freemium',
    useCases: ['背景音乐', '歌曲创作', '内容配乐', '创意实验', '个人娱乐'],
    prosCons: { pros: ['生成质量高', '多种风格', '人声自然', '操作简单', '免费额度'], cons: ['版权存疑', '歌词生硬', '免费有限制', '定制困难', '商业授权贵'] },
    officialUrl: 'https://suno.ai',
    score: 9.1,
  },
  {
    id: 'hugging-face',
    name: 'Hugging Face',
    description: '全球最大的 AI 模型社区和平台。提供 50 万+ 预训练模型、数据集和 AI 应用。支持模型部署和 API。',
    shortDesc: '全球最大 AI 模型社区',
    url: 'https://huggingface.co',
    category: 'code',
    tags: ['AI 平台', '开源模型', '开发者', 'API', '社区'],
    pricing: 'freemium',
    useCases: ['模型部署', 'API 调用', '模型微调', 'AI 研究', '项目展示'],
    prosCons: { pros: ['模型丰富', '社区活跃', '免费部署', '文档完善', '易上手指南'], cons: ['免费算力限', '企业版贵', '模型质量参差', '平台复杂', 'GPU 贵'] },
    officialUrl: 'https://huggingface.co',
    score: 9.2,
  },
  {
    id: 'replit',
    name: 'Replit',
    description: '云端 AI 编程环境，支持浏览器内编码、运行和部署。Ghostwriter AI 提供代码补全和调试。',
    shortDesc: '云端 AI 编程与部署平台',
    url: 'https://replit.com',
    category: 'code',
    tags: ['云端 IDE', 'AI 编程', '快速原型', '协作', '部署'],
    pricing: 'freemium',
    useCases: ['快速原型', '学习编程', '团队协作', '小项目部署', 'AI 辅助开发'],
    prosCons: { pros: ['无需配置', '即时部署', '协作方便', 'Ghostwriter', '多语言'], cons: ['性能有限', '免费版慢', '不适合大项目', '付费较高', '离线差'] },
    officialUrl: 'https://replit.com',
    score: 8.6,
  },
  {
    id: 'adobe-firefly',
    name: 'Adobe Firefly',
    description: 'Adobe 的生成式 AI 工具集，集成在 Photoshop、Illustrator 等 Creative Cloud 应用中。',
    shortDesc: 'Adobe 全家桶 AI 创意工具',
    url: 'https://firefly.adobe.com',
    category: 'image',
    tags: ['Adobe', '生成式填充', '设计工具', '创意云', '商业安全'],
    pricing: 'paid',
    useCases: ['图像编辑', '文字特效', '矢量生成', '3D 设计', '商业创作'],
    prosCons: { pros: ['Adobe 集成', '商业安全', '高质量输出', '专业工具', '版权保护'], cons: ['需订阅 CC', '独立版弱', '功能分散', '生成速度慢', '限制较严'] },
    officialUrl: 'https://firefly.adobe.com',
    score: 8.8,
  },
  {
    id: 'copilot-microsoft',
    name: 'Microsoft Copilot',
    description: '微软 AI 助手，集成在 Windows、Office 365、Edge 浏览器中。支持文档编写、数据分析、邮件处理。',
    shortDesc: '微软全平台 AI 助手',
    url: 'https://copilot.microsoft.com',
    category: 'productivity',
    tags: ['Office 集成', 'AI 助手', '企业工具', 'Windows', '办公'],
    pricing: 'freemium',
    useCases: ['办公自动化', '文档编写', '数据分析', '会议总结', '邮件管理'],
    prosCons: { pros: ['全平台集成', 'Office 深度', '企业安全', '数据分析', '会议辅助'], cons: ['免费功能少', '企业版贵', 'Windows 绑定', '竞品对比', '功能分散'] },
    officialUrl: 'https://copilot.microsoft.com',
    score: 8.8,
  },
  {
    id: 'descript',
    name: 'Descript',
    description: 'AI 音视频编辑工具，像编辑文档一样编辑视频。支持自动转录、文本编辑视频、AI 配音。',
    shortDesc: '像编辑文档一样编辑视频',
    url: 'https://www.descript.com',
    category: 'video',
    tags: ['视频编辑', '播客工具', '转录', 'AI 配音', '屏幕录制'],
    pricing: 'freemium',
    useCases: ['播客制作', '视频剪辑', '转录字幕', '内容创作', '远程课程'],
    prosCons: { pros: ['文本编辑视频', '自动转录', 'AI 配音', '界面创新', '协作方便'], cons: ['高级功能付费', '复杂编辑弱', '中文转录差', '导出限制', '学习成本'] },
    officialUrl: 'https://www.descript.com',
    score: 8.6,
  },
  {
    id: 'ideo-gram',
    name: 'Ideogram',
    description: 'AI 图像生成工具，在文字渲染方面表现突出。可生成带精确文字的 Logo、海报和社交媒体图片。',
    shortDesc: '文字渲染最强的 AI 图像生成',
    url: 'https://ideogram.ai',
    category: 'image',
    tags: ['AI 绘图', '文字渲染', 'Logo 设计', '海报', 'AI 设计'],
    pricing: 'freemium',
    useCases: ['Logo 设计', '海报制作', '社媒配图', '品牌视觉', '产品展示'],
    prosCons: { pros: ['文字渲染最强', '多种风格', '免费可用', 'Prompt 理解好', '无需 Discord'], cons: ['免费有限', '分辨率不高', '通用性不如 Midjourney', '风格受限', '新功能慢'] },
    officialUrl: 'https://ideogram.ai',
    score: 8.6,
  },
  {
    id: 'sourcegraph-cody',
    name: 'Sourcegraph Cody',
    description: '基于完整代码库理解的 AI 编程助手。理解整个仓库的代码结构，提供上下文相关的代码补全和解释。',
    shortDesc: '全代码库理解的 AI 编程助手',
    url: 'https://sourcegraph.com',
    category: 'code',
    tags: ['代码搜索', '代码审查', 'AI 编程', '代码库理解', '开发者工具'],
    pricing: 'freemium',
    useCases: ['大型项目重构', '遗留代码理解', '测试生成', '代码审查', '项目入职'],
    prosCons: { pros: ['完整代码上下文', '多仓库支持', '复杂代码解释', '测试生成', '私有部署'], cons: ['配置复杂', '企业导向', '免费限制', '资源消耗大', '学习曲线'] },
    officialUrl: 'https://sourcegraph.com',
    score: 8.9,
  },
  {
    id: 'tabnine',
    name: 'Tabnine',
    description: '注重隐私的 AI 代码补全工具，支持本地模型运行。覆盖 90+ 编程语言和 15+ IDE。',
    shortDesc: '隐私优先的 AI 代码补全',
    url: 'https://tabnine.com',
    category: 'code',
    tags: ['AI 代码补全', '隐私', 'IDE 插件', '企业', '本地模型'],
    pricing: 'freemium',
    useCases: ['日常开发', '代码补全', '企业开发', '学习框架', '安全开发'],
    prosCons: { pros: ['隐私保护', '本地模型', '私有部署', '多语言', 'IDE 支持广'], cons: ['准确性不如云', '高级版贵', '上下文有限', '比 Copilot 慢', '免费功能少'] },
    officialUrl: 'https://tabnine.com',
    score: 8.5,
  },
  {
    id: 'codeium',
    name: 'Codeium (Windsurf)',
    description: '免费 AI 代码助手，无限补全。支持 70+ 语言和 40+ IDE。包含代码搜索、AI 对话和 Windsurf IDE。',
    shortDesc: '免费的 AI 代码助手',
    url: 'https://codeium.com',
    category: 'code',
    tags: ['免费 AI 编程', '代码补全', 'IDE 插件', '代码搜索', '开发者工具'],
    pricing: 'free',
    useCases: ['日常开发', '代码搜索', '学习新语言', '快速原型', '代码理解'],
    prosCons: { pros: ['完全免费', '多语言', '代码搜索', 'Windsurf IDE', '无需信用卡'], cons: ['准确性不如付费', '社区较小', '隐私问题', '上下文窗口小', '较新平台'] },
    officialUrl: 'https://codeium.com',
    score: 8.6,
  },
  {
    id: 'amazon-q',
    name: 'Amazon Q Developer',
    description: 'AWS 出品的 AI 编程助手（原 CodeWhisperer）。在 AWS 基础设施代码方面表现优异。',
    shortDesc: 'AWS 原生 AI 编程助手',
    url: 'https://aws.amazon.com/q/developer/',
    category: 'code',
    tags: ['AWS', '代码安全', '基础设施代码', 'AI 编程', '云开发'],
    pricing: 'freemium',
    useCases: ['AWS 开发', '安全扫描', 'Lambda 开发', 'CloudFormation', '通用编码'],
    prosCons: { pros: ['AWS 专精', '安全扫描', '个人免费', 'SDK 理解', '基础设施代码'], cons: ['AWS 绑定', '通用编码弱', 'IDE 支持少', '建议较慢', '平台锁定'] },
    officialUrl: 'https://aws.amazon.com/q/developer/',
    score: 8.4,
  },
  {
    id: 'zed-ai',
    name: 'Zed AI',
    description: 'Rust 编写的高性能代码编辑器，内置 AI 结对编程。支持 Claude 和 GPT 模型。',
    shortDesc: '高性能 AI 代码编辑器',
    url: 'https://zed.dev',
    category: 'code',
    tags: ['代码编辑器', 'Rust', 'AI 编程', '高性能', '开发者'],
    pricing: 'freemium',
    useCases: ['快速编码', 'AI 编程', '大型项目导航', '团队协作', '实时分享'],
    prosCons: { pros: ['极快速度', 'Rust 构建', 'AI 差异显示', '多模型', '协作功能'], cons: ['早期阶段', '插件生态小', 'Mac 为主', '无 Windows 版', '学习新编辑器'] },
    officialUrl: 'https://zed.dev',
    score: 8.7,
  },
  {
    id: 'veed-io',
    name: 'VEED.io',
    description: '浏览器端 AI 视频编辑工具。自动字幕、背景移除、降噪和眼神校正。支持屏幕录制。',
    shortDesc: '浏览器 AI 视频编辑器',
    url: 'https://veed.io',
    category: 'video',
    tags: ['视频编辑', '自动字幕', '浏览器', '屏幕录制', '社交视频'],
    pricing: 'freemium',
    useCases: ['社媒短视频', '字幕生成', '屏幕录制', '营销视频', '快速剪辑'],
    prosCons: { pros: ['无需安装', '字幕准确', '背景移除', '眼神修正', '社交模板'], cons: ['免费水印', '导出限制', '处理慢', '高级版贵', '复杂剪辑弱'] },
    officialUrl: 'https://veed.io',
    score: 8.8,
  },
  {
    id: 'opus-clip',
    name: 'Opus Clip',
    description: 'AI 视频再创作工具，从长视频中提取高光片段。自动生成带字幕的短视频格式。',
    shortDesc: '长视频自动转短视频 AI 工具',
    url: 'https://opus.pro',
    category: 'video',
    tags: ['视频再创作', '短视频', '自动剪辑', '字幕', '创作者'],
    pricing: 'freemium',
    useCases: ['YouTube 转 Shorts', '播客剪辑', '社媒再创作', '网络研讨会', '内容营销'],
    prosCons: { pros: ['自动提取', '智能高光', '自动字幕', '竖屏格式', '节省时间'], cons: ['量大价高', '免费限制', '选择不准', '无精细编辑', '品牌水印'] },
    officialUrl: 'https://opus.pro',
    score: 8.7,
  },
  {
    id: 'capcut',
    name: 'CapCut',
    description: '字节跳动出品的免费视频编辑应用，集成 AI 功能。自动字幕、文字转语音、背景移除。',
    shortDesc: '免费 AI 视频编辑（TikTok 官方）',
    url: 'https://capcut.com',
    category: 'video',
    tags: ['视频编辑', '免费', 'TikTok', '移动端', '模板'],
    pricing: 'free',
    useCases: ['TikTok 创作', '社媒编辑', '自动字幕', '模板视频', '移动剪辑'],
    prosCons: { pros: ['完全免费', '移动端优秀', '自动字幕', '海量模板', 'TikTok 集成'], cons: ['隐私顾虑', '桌面端弱', 'AI 功能有限', '导出压缩', '偶尔广告'] },
    officialUrl: 'https://capcut.com',
    score: 8.9,
  },
  {
    id: 'anyword',
    name: 'Anyword',
    description: 'AI 文案平台，发布前预测内容效果。为营销团队提供数据驱动的文案优化。',
    shortDesc: 'AI 营销文案与效果预测',
    url: 'https://anyword.com',
    category: 'marketing',
    tags: ['AI 文案', '转化优化', '营销分析', '广告文案', '效果预测'],
    pricing: 'paid',
    useCases: ['广告文案优化', '邮件营销', '着陆页', '社媒广告', '转化提升'],
    prosCons: { pros: ['效果预测', '数据驱动', '多版本', '渠道优化', '团队协作'], cons: ['价格较高', '短文本为主', '学习曲线', '过度依赖分数', '模板有限'] },
    officialUrl: 'https://anyword.com',
    score: 8.5,
  },
  {
    id: 'writer',
    name: 'Writer AI',
    description: '企业级 AI 内容平台，确保品牌信息一致性。强制执行风格指南。',
    shortDesc: '企业级品牌内容 AI 平台',
    url: 'https://writer.com',
    category: 'marketing',
    tags: ['企业 AI', '品牌一致', '风格指南', '营销 AI', '合规'],
    pricing: 'paid',
    useCases: ['企业内容创作', '品牌合规', '营销文案', '内部沟通', '文档生成'],
    prosCons: { pros: ['品牌执行', '企业安全', '自定义 LLM', '合规功能', '风格集成'], cons: ['价格贵', '企业导向', '小团队贵', '免费有限', '学习成本'] },
    officialUrl: 'https://writer.com',
    score: 8.6,
  },
  {
    id: 'surfer-seo',
    name: 'Surfer SEO',
    description: 'AI 内容优化平台提升搜索排名。数据驱动内容简报和 NLP 关键词研究。',
    shortDesc: 'AI SEO 内容优化',
    url: 'https://surferseo.com',
    category: 'marketing',
    tags: ['SEO', '内容优化', '关键词研究', '排名提升', '写作工具'],
    pricing: 'paid',
    useCases: ['SEO 内容优化', '关键词研究', '内容简报', '页面 SEO', '内容评分'],
    prosCons: { pros: ['数据驱动', 'NLP 研究', '内容评分', 'Google Doc 集成', 'WordPress 插件'], cons: ['价格高', '无免费版', '数据过多', '短内容弱', '仅 SEO 专注'] },
    officialUrl: 'https://surferseo.com',
    score: 8.7,
  },
  {
    id: 'frase',
    name: 'Frase AI',
    description: 'AI 内容研究与 SEO 写作助手。从 SERP 生成内容简报撰写 SEO 文章。',
    shortDesc: 'AI SEO 内容研究与写作',
    url: 'https://frase.io',
    category: 'marketing',
    tags: ['SEO 内容', '内容简报', 'AI 写作', '关键词研究', '内容优化'],
    pricing: 'paid',
    useCases: ['SEO 文章', '内容研究', 'SERP 分析', '内容简报', '博客写作'],
    prosCons: { pros: ['SERP 分析', '自动简报', '内容评分', '大纲生成', '工具集成'], cons: ['价格高', '需人工编辑', '无免费版', '学习曲线', '有时生成普通'] },
    officialUrl: 'https://frase.io',
    score: 8.6,
  },
  {
    id: 'resemble',
    name: 'Resemble AI',
    description: '专业 AI 语音克隆和音频生成。自定义声音实时语音合成情感 TTS。',
    shortDesc: '专业 AI 语音克隆与生成',
    url: 'https://resemble.ai',
    category: 'audio',
    tags: ['语音克隆', 'TTS', 'AI 语音', '音频生成', 'API'],
    pricing: 'freemium',
    useCases: ['语音克隆', '旁白制作', '配音创作', '语音翻译', '音频内容'],
    prosCons: { pros: ['高质量克隆', '情感 TTS', 'API 访问', '设计工作室', '实时合成'], cons: ['企业版贵', '免费限制', '处理时间', '质量不一', '需技术配置'] },
    officialUrl: 'https://resemble.ai',
    score: 8.6,
  },
  {
    id: 'play-ht',
    name: 'PlayHT',
    description: '900+ AI 语音的文字转语音平台。100+ 语言语音克隆实时流式音频。',
    shortDesc: '900+ AI 语音的 TTS 平台',
    url: 'https://play.ht',
    category: 'audio',
    tags: ['TTS', '文字转语音', '语音生成', '有声书', '内容创作者'],
    pricing: 'paid',
    useCases: ['配音制作', '有声书旁白', '播客创作', '在线教育', '内容配音'],
    prosCons: { pros: ['900+ 声音', '100+ 语言', '逼真质量', '流式 API', '商业授权'], cons: ['无免费版', '仅付费', '语音克隆加价', '额度制', '竞争增多'] },
    officialUrl: 'https://play.ht',
    score: 8.7,
  },
  {
    id: 'wellsaid',
    name: 'WellSaid Labs',
    description: '工作室级 AI 配音平台。高质量声音角色语速调节团队协作品牌管理。',
    shortDesc: '工作室级 AI 配音平台',
    url: 'https://wellsaidlabs.com',
    category: 'audio',
    tags: ['语音生成', '配音', '企业 TTS', '工作室级', '内容'],
    pricing: 'paid',
    useCases: ['专业配音', '在线教育', '企业培训', '有声书', '品牌音频'],
    prosCons: { pros: ['工作室品质', '声音多样', '团队协作', '品牌管理', 'SOC 2'], cons: ['价格较贵', '无免费版', '预览有限', '声音选项少', '企业导向'] },
    officialUrl: 'https://wellsaidlabs.com',
    score: 8.6,
  },
  {
    id: 'murf-ai',
    name: 'Murf AI',
    description: 'AI 语音生成平台 120+ 自然语音。语音克隆多语言内置视频编辑器。',
    shortDesc: 'AI 语音生成与视频配音平台',
    url: 'https://murf.ai',
    category: 'audio',
    tags: ['AI 语音', '视频配音', '有声内容', '教育', '营销'],
    pricing: 'freemium',
    useCases: ['视频配音', '有声内容', '教育培训', '商业演示', '播客'],
    prosCons: { pros: ['语音自然', '视频同步', '语音克隆', '多语言', 'API 支持'], cons: ['免费有限', '付费较贵', '中文口音差', '长文本贵', '竞争激烈'] },
    officialUrl: 'https://murf.ai',
    score: 8.4,
  },
  {
    id: 'aiva',
    name: 'AIVA AI Music',
    description: 'AI 音乐作曲助手为配乐和背景音乐创作。基于古典和电影配乐训练。',
    shortDesc: 'AI 音乐作曲与配乐',
    url: 'https://aiva.ai',
    category: 'audio',
    tags: ['AI 音乐', '作曲', '配乐', '免版税', '创作'],
    pricing: 'freemium',
    useCases: ['背景音乐', '配乐创作', '内容音乐', '播客音乐', '游戏音频'],
    prosCons: { pros: ['音乐理论', '电影级质量', '风格定制', '版权全拥有', 'MIDI 导出'], cons: ['免费限制', '订阅费用', '控制力有限', '偏古典', '定制复杂'] },
    officialUrl: 'https://aiva.ai',
    score: 8.4,
  },
  {
    id: 'voicemod-ai',
    name: 'Voicemod AI',
    description: '实时 AI 变声器适用于游戏直播和内容创作。上百种声音滤镜。',
    shortDesc: '实时 AI 变声器',
    url: 'https://voicemod.net',
    category: 'audio',
    tags: ['变声器', '实时音频', '游戏', '直播', '音频工具'],
    pricing: 'freemium',
    useCases: ['游戏语音', '直播娱乐', '内容创作', '虚拟活动', '社交音频'],
    prosCons: { pros: ['实时处理', '声音丰富', '音板功能', '直播集成', '社区预设'], cons: ['免费限制', '免费版质降', '资源消耗', '延迟偶发', '非专业级'] },
    officialUrl: 'https://voicemod.net',
    score: 8.5,
  },
  {
    id: 'you-com',
    name: 'You.com',
    description: 'AI 搜索引擎结合网页搜索对话代码生成和图像创建。多模型平台。',
    shortDesc: '多模型 AI 搜索引擎',
    url: 'https://you.com',
    category: 'search',
    tags: ['AI 搜索', '网页搜索', '代码生成', 'AI 对话', '开发者'],
    pricing: 'freemium',
    useCases: ['AI 研究', '代码搜索', '联网对话', '图像生成', '多模型使用'],
    prosCons: { pros: ['多模型', '代码生成', '搜索集成', '图像生成', 'API 支持'], cons: ['免费有限', '部分付费', '用户较少', '搜索质量一般', '竞争激烈'] },
    officialUrl: 'https://you.com',
    score: 8.6,
  },
  {
    id: 'consensus',
    name: 'Consensus',
    description: 'AI 学术搜索引擎从同行评审论文中提取见解。提供研究问题共识答案。',
    shortDesc: 'AI 学术搜索引擎',
    url: 'https://consensus.app',
    category: 'search',
    tags: ['学术搜索', '研究', '科学论文', '证据查询', '教育'],
    pricing: 'freemium',
    useCases: ['研究问题', '文献综述', '学术写作', '论文发现', '证据收集'],
    prosCons: { pros: ['同行评审', '论文摘要', '共识答案', '引用导出', '无广告'], cons: ['免费查询少', '未覆盖全部', '搜索范围窄', '学术专用', '无全文'] },
    officialUrl: 'https://consensus.app',
    score: 8.8,
  },
  {
    id: 'elicit',
    name: 'Elicit AI',
    description: 'AI 研究助手自动化文献综述。从论文提取关键发现总结结论。',
    shortDesc: 'AI 文献综述与研究助手',
    url: 'https://elicit.com',
    category: 'search',
    tags: ['学术研究', '文献综述', '论文分析', 'AI 研究', '教育'],
    pricing: 'freemium',
    useCases: ['文献综述', '论文发现', '研究综合', '引用管理', '基金写作'],
    prosCons: { pros: ['论文理解', '发现提取', '相关性排序', '节省时间', '导出功能'], cons: ['免费很低', '非全部论文', '高级版贵', '提取不完美', '仅研究专用'] },
    officialUrl: 'https://elicit.com',
    score: 8.8,
  },
  {
    id: 'phind',
    name: 'Phind',
    description: '面向开发者的 AI 搜索引擎。搜索网页生成含代码片段的解答。',
    shortDesc: '开发者 AI 搜索引擎',
    url: 'https://phind.com',
    category: 'search',
    tags: ['开发者搜索', '技术问答', '代码搜索', '文档', '效率'],
    pricing: 'freemium',
    useCases: ['技术排错', '代码文档', '开发问题', 'Bug 解决', '技术研究'],
    prosCons: { pros: ['开发者专精', '代码生成', '搜索集成', '上下文保持', '响应快'], cons: ['免费有限', '代码准确性不一', '技术专用', '较新平台', 'SaaS 依赖'] },
    officialUrl: 'https://phind.com',
    score: 8.6,
  },
  {
    id: 'otter',
    name: 'Otter.ai',
    description: 'AI 会议助手自动转录总结会议提取行动项。支持 Zoom Google Meet。',
    shortDesc: 'AI 会议助手与转录',
    url: 'https://otter.ai',
    category: 'productivity',
    tags: ['会议助手', '转录', '会议记录', '团队协作', '效率'],
    pricing: 'freemium',
    useCases: ['会议转录', '会议笔记', '协作', '面试记录', '团队沟通'],
    prosCons: { pros: ['实时转录', '说话人识别', '自动总结', '会议集成', '可搜索'], cons: ['免费限制', '口音挑战', '无离线', '隐私问题', '导出限制'] },
    officialUrl: 'https://otter.ai',
    score: 8.8,
  },
  {
    id: 'fireflies',
    name: 'Fireflies.ai',
    description: 'AI 会议记录器在 20+ 平台自动加入会议录制转录生成笔记。CRM 集成。',
    shortDesc: 'AI 会议记录与智能分析',
    url: 'https://fireflies.ai',
    category: 'productivity',
    tags: ['会议助手', '对话智能', '转录', 'CRM 集成', '效率'],
    pricing: 'freemium',
    useCases: ['会议录制', '销售分析', 'CRM 同步', '团队协作', '会议笔记'],
    prosCons: { pros: ['20+ 平台', 'CRM 集成', '可搜索转录', '话题追踪', '精彩片段'], cons: ['免费限制', '设置复杂', '准确性不一', '高级版贵', '隐私顾虑'] },
    officialUrl: 'https://fireflies.ai',
    score: 8.7,
  },
  {
    id: 'motion',
    name: 'Motion',
    description: 'AI 效率应用自动规划每日日程。根据优先级创建最优时间表。',
    shortDesc: 'AI 自动日程规划应用',
    url: 'https://usemotion.com',
    category: 'productivity',
    tags: ['项目管理', '日程安排', '日历 AI', '时间管理', '效率'],
    pricing: 'paid',
    useCases: ['日常规划', '项目管理', '会议安排', '任务优先', '团队管理'],
    prosCons: { pros: ['自动排程', '智能优先', '日历同步', '截止管理', '团队空间'], cons: ['仅付费贵', '学习曲线', '不够灵活', '时区问题', '过度工程'] },
    officialUrl: 'https://usemotion.com',
    score: 8.6,
  },
  {
    id: 'mem-ai',
    name: 'Mem.ai',
    description: 'AI 知识管理平台自动组织笔记。自动关联建议连接自动标签。',
    shortDesc: '自动组织的 AI 知识管理',
    url: 'https://mem.ai',
    category: 'productivity',
    tags: ['知识管理', '笔记', 'AI 组织', '个人知识', '工作空间'],
    pricing: 'freemium',
    useCases: ['个人笔记', '知识库', '研究整理', '内容策划', '团队知识'],
    prosCons: { pros: ['自动整理', 'AI 建议', '关联发现', '界面简洁', '搜索快'], cons: ['免费限制', '需订阅', '导出有限', '新平台 Bug', '重度用户弱'] },
    officialUrl: 'https://mem.ai',
    score: 8.5,
  },
  {
    id: 'taskade',
    name: 'Taskade',
    description: 'AI 协作工作空间。任务管理笔记思维导图。AI 自动生成项目计划。',
    shortDesc: 'AI 协作工作空间',
    url: 'https://taskade.com',
    category: 'productivity',
    tags: ['协作', '任务管理', 'AI 工作流', '思维导图', '团队'],
    pricing: 'freemium',
    useCases: ['项目管理', '团队协作', '任务分配', '思维导图', '工作流自动化'],
    prosCons: { pros: ['功能全面', 'AI 项目生成', '实时协作', '思维导图', '模板丰富'], cons: ['界面复杂', '免费限制', 'AI 功能需付费', '移动端弱', '学习曲线'] },
    officialUrl: 'https://taskade.com',
    score: 8.4,
  },
  {
    id: 'fathom',
    name: 'Fathom AI',
    description: 'AI 笔记助手带 CRM 集成。自动录制转录会议生成笔记摘要。免费版可用。',
    shortDesc: 'AI 会议笔记与 CRM 集成',
    url: 'https://fathom.video',
    category: 'productivity',
    tags: ['会议笔记', '视频通话', '转录', 'CRM', '效率'],
    pricing: 'free',
    useCases: ['会议记录', '销售通话', '客户管理', '笔记自动', '团队沟通'],
    prosCons: { pros: ['完全免费核心', '自动录制', 'CRM 集成', 'AI 笔记', '使用简单'], cons: ['功能深度不够', '平台兼容少', '分析功能弱', '企业功能少', '较新'] },
    officialUrl: 'https://fathom.video',
    score: 8.5,
  },
  {
    id: 'zapier-central',
    name: 'Zapier Central AI',
    description: 'AI 自动化平台连接 6000+ 应用。自然语言执行跨应用工作流。',
    shortDesc: 'AI 无代码工作流自动化',
    url: 'https://zapier.com',
    category: 'productivity',
    tags: ['自动化', '无代码', '应用集成', 'AI 代理', '效率'],
    pricing: 'freemium',
    useCases: ['跨应用自动化', '数据同步', '任务自动', '邮件自动', 'CRM 更新'],
    prosCons: { pros: ['应用丰富', 'AI 代理', '无代码操作', '模板丰富', '企业方案'], cons: ['免费限制', '复杂场景贵', '学习曲线', '调试困难', '速度受限'] },
    officialUrl: 'https://zapier.com',
    score: 8.7,
  },
  {
    id: 'make',
    name: 'Make (Integromat)',
    description: '可视化自动化平台拖拽创建复杂自动化场景。2000+ 应用集成。',
    shortDesc: '可视化 AI 自动化平台',
    url: 'https://www.make.com',
    category: 'productivity',
    tags: ['自动化', '可视化', '应用集成', '工作流', '无代码'],
    pricing: 'freemium',
    useCases: ['复杂自动化', '数据转换', '应用集成', '报表更新', '通知系统'],
    prosCons: { pros: ['可视化强', '逻辑灵活', '应用丰富', '数据处理', '场景共享'], cons: ['学习曲线陡', '免费限制', '调试复杂', '执行速度', '高级版贵'] },
    officialUrl: 'https://www.make.com',
    score: 8.6,
  },
  {
    id: 'bardeen',
    name: 'Bardeen AI',
    description: 'AI 工作流自动化工具无需编码。浏览器扩展一键触发自动化。',
    shortDesc: 'AI 无代码工作流自动化',
    url: 'https://bardeen.ai',
    category: 'productivity',
    tags: ['工作流自动化', '无代码', '效率', '应用集成', 'AI'],
    pricing: 'freemium',
    useCases: ['数据抓取', '邮件自动化', 'CRM 更新', '社媒管理', '报表生成'],
    prosCons: { pros: ['无需编码', 'AI 操作', '浏览器扩展', '一键触发', '预建模板'], cons: ['免费限制', '复杂场景弱', '浏览器依赖', '应用覆盖有限', '学习曲线'] },
    officialUrl: 'https://bardeen.ai',
    score: 8.3,
  },
  {
    id: 'rytr',
    name: 'Rytr',
    description: '高性价比 AI 写作助手。40+ 模板 30+ 语言。博客邮件广告社媒文案。',
    shortDesc: '高性价比 AI 写作助手',
    url: 'https://rytr.me',
    category: 'writing',
    tags: ['AI 写作', '内容创作', '文案', '多语言', '性价比'],
    pricing: 'freemium',
    useCases: ['博客写作', '邮件文案', '广告文案', '社媒内容', '产品描述'],
    prosCons: { pros: ['价格实惠', '多模板', '多语言', '使用简单', '输出快速'], cons: ['质量一般', '需编辑', '免费字数限制', '高级版受限', '深度不足'] },
    officialUrl: 'https://rytr.me',
    score: 8.3,
  },
  {
    id: 'sudowrite',
    name: 'Sudowrite',
    description: '专为小说作者设计的 AI 写作工具。故事创作角色发展和情节构思。',
    shortDesc: '小说创作 AI 写作助手',
    url: 'https://www.sudowrite.com',
    category: 'writing',
    tags: ['创意写作', '小说', '故事创作', '写作辅助', '文学'],
    pricing: 'paid',
    useCases: ['小说创作', '故事构建', '角色发展', '情节设计', '创意写作'],
    prosCons: { pros: ['创意强大', '故事理解', '写作风格多样', '专注小说', '功能丰富'], cons: ['价格较高', '无免费版', '学习曲线', '非小说弱', '英文为主'] },
    officialUrl: 'https://www.sudowrite.com',
    score: 8.6,
  },
  {
    id: 'quillbot',
    name: 'QuillBot',
    description: 'AI 改写和写作改进工具。改写语法检查摘要生成和引用功能。',
    shortDesc: 'AI 改写与写作改进',
    url: 'https://quillbot.com',
    category: 'writing',
    tags: ['改写', '语法检查', '摘要', '学术写作', '写作工具'],
    pricing: 'freemium',
    useCases: ['文章改写', '语法纠错', '内容摘要', '学术写作', '引用生成'],
    prosCons: { pros: ['改写质量高', '免费可用', '语法检查准', '摘要功能', '扩展安装'], cons: ['免费字数限制', '高级版贵', '有时语义改变', '英文为主', '过度依赖'] },
    officialUrl: 'https://quillbot.com',
    score: 8.7,
  },
  {
    id: 'wordtune',
    name: 'Wordtune',
    description: 'AI 重写工具让写作更清晰。多种改写方式调整语气和风格。',
    shortDesc: 'AI 重写与写作改进',
    url: 'https://www.wordtune.com',
    category: 'writing',
    tags: ['重写', '写作改进', '语气调整', '浏览器扩展', '编辑'],
    pricing: 'freemium',
    useCases: ['文章重写', '语气调整', '邮件优化', '学术写作', '专业沟通'],
    prosCons: { pros: ['多种改写方式', '语气控制', '浏览器集成', '实时建议', '跨平台'], cons: ['免费有限', '高级版贵', '中文支持差', '偶尔建议不当', '输出需校对'] },
    officialUrl: 'https://www.wordtune.com',
    score: 8.5,
  },
  {
    id: 'kittl',
    name: 'Kittl AI',
    description: 'AI 设计工具专注文字效果和品牌图形设计。提供模板和 AI 生成功能。',
    shortDesc: 'AI 文字效果与品牌设计',
    url: 'https://www.kittl.com',
    category: 'image',
    tags: ['设计', '文字效果', '品牌图形', '印刷品', '社媒设计'],
    pricing: 'freemium',
    useCases: ['Logo 设计', '品牌视觉', '海报制作', '印刷品', '社媒配图'],
    prosCons: { pros: ['文字特效强', '操作简单', '模板丰富', '品牌工具', 'AI 辅助'], cons: ['免费限制', '高级版贵', '矢量编辑弱', '新平台', '功能待完善'] },
    officialUrl: 'https://www.kittl.com',
    score: 8.3,
  },
  {
    id: 'remove-bg',
    name: 'Remove.bg',
    description: 'AI 背景移除工具精准识别主体并去除背景。支持批量处理和 API。',
    shortDesc: 'AI 精准背景移除',
    url: 'https://www.remove.bg',
    category: 'image',
    tags: ['背景移除', '图像处理', '照片编辑', '电商工具', 'API'],
    pricing: 'freemium',
    useCases: ['产品照片', '人物抠图', '证件照', '电商图片', '设计素材'],
    prosCons: { pros: ['精准度高', '处理快速', 'API 完善', '批量处理', '使用简单'], cons: ['免费分辨率低', '付费较贵', '批量计费', '无法精细调整', '仅单一功能'] },
    officialUrl: 'https://www.remove.bg',
    score: 8.8,
  },
  {
    id: 'clipdrop',
    name: 'ClipDrop',
    description: 'AI 图像编辑工具集。背景移除图像放大照明调整一键清理照片。',
    shortDesc: 'AI 图像编辑与增强',
    url: 'https://clipdrop.co',
    category: 'image',
    tags: ['图像编辑', '背景移除', '图像放大', '照片优化', 'AI 工具'],
    pricing: 'freemium',
    useCases: ['产品照片优化', '背景移除', '图像放大', '电商图片', '设计素材'],
    prosCons: { pros: ['一键操作', '背景移除精准', '图像增强', 'API 支持', '实时处理'], cons: ['免费限制', '高级版贵', '分辨率限制', '批量付费', '功能集中'] },
    officialUrl: 'https://clipdrop.co',
    score: 8.5,
  },
  {
    id: 'lets-enhance',
    name: "Let's Enhance",
    description: 'AI 图像放大增强工具增加真实细节。支持图像放大修复和色彩优化。',
    shortDesc: 'AI 图像放大与细节增强',
    url: 'https://letsenhance.io',
    category: 'image',
    tags: ['图像放大', '增强', '照片修复', '画质提升', 'AI'],
    pricing: 'freemium',
    useCases: ['图像放大', '老照片修复', '画质提升', '打印输出', '电商图片'],
    prosCons: { pros: ['细节增强', '多种模式', '批量处理', 'API 支持', '质量好'], cons: ['免费限制', '付费较贵', '处理时间', '不适合动画', '过度锐化'] },
    officialUrl: 'https://letsenhance.io',
    score: 8.5,
  },
  {
    id: 'cutout-pro',
    name: 'Cutout Pro',
    description: 'AI 视觉设计平台集成背景移除图像修复视频编辑 AI 头像生成。',
    shortDesc: 'AI 视觉设计与编辑平台',
    url: 'https://www.cutout.pro',
    category: 'image',
    tags: ['视觉设计', '背景移除', '图像修复', 'AI 头像', '视频编辑'],
    pricing: 'freemium',
    useCases: ['背景移除', '老照片修复', '头像生成', '视频编辑', '电商设计'],
    prosCons: { pros: ['功能丰富', 'AI 头像', '修复效果好', '多语言', 'API 支持'], cons: ['免费有限', '质量不一', '处理较慢', '界面复杂', '高级功能贵'] },
    officialUrl: 'https://www.cutout.pro',
    score: 8.3,
  },
  {
    id: 'langchain',
    name: 'LangChain',
    description: 'AI 应用开发框架简化 LLM 应用构建。链式调用 Agent RAG 工具调用。',
    shortDesc: 'AI 应用开发框架',
    url: 'https://www.langchain.com',
    category: 'code',
    tags: ['AI 框架', 'LLM', '开源', 'Agent', 'RAG'],
    pricing: 'free',
    useCases: ['AI 应用开发', 'Agent 构建', 'RAG 系统', '工具链', '原型开发'],
    prosCons: { pros: ['开源免费', '社区活跃', '功能全面', '多模型支持', '生态丰富'], cons: ['学习曲线陡', '更新频繁', '调试困难', '文档更新慢', '抽象太重'] },
    officialUrl: 'https://www.langchain.com',
    score: 8.9,
  },
  {
    id: 'cohere',
    name: 'Cohere',
    description: '企业级 AI 平台专注 RAG 和企业搜索。Embedding Rerank 生成 API。',
    shortDesc: '企业级 RAG 与搜索 AI 平台',
    url: 'https://cohere.com',
    category: 'code',
    tags: ['企业 AI', 'RAG', '嵌入', '搜索', 'API'],
    pricing: 'freemium',
    useCases: ['企业搜索', '文档检索', '智能问答', '内容分类', '语义理解'],
    prosCons: { pros: ['RAG 专精', '企业安全', 'API 完善', '文档处理', '多语言'], cons: ['价格较高', '通用对话弱', '开发知识要求', '免费限制', '竞品多'] },
    officialUrl: 'https://cohere.com',
    score: 8.7,
  },
  {
    id: 'pinecone',
    name: 'Pinecone',
    description: '向量数据库服务专为 AI 应用设计。存储搜索向量嵌入语义搜索和 RAG。',
    shortDesc: 'AI 向量数据库服务',
    url: 'https://www.pinecone.io',
    category: 'code',
    tags: ['向量数据库', 'AI 基础设施', '搜索', '嵌入', 'RAG'],
    pricing: 'freemium',
    useCases: ['语义搜索', 'RAG 应用', '推荐系统', '相似度匹配', 'AI 记忆'],
    prosCons: { pros: ['高性能', '实时搜索', '易于使用', '托管服务', '文档好'], cons: ['免费限制', '量大价高', '供应商绑定', '仅向量存储', '学习曲线'] },
    officialUrl: 'https://www.pinecone.io',
    score: 8.8,
  },
  {
    id: 'n8n',
    name: 'n8n',
    description: '开源工作流自动化工具可自托管。400+ 节点代码可控注重隐私。',
    shortDesc: '开源可自托管的自动化平台',
    url: 'https://n8n.io',
    category: 'code',
    tags: ['开源', '自动化', '自托管', '工作流', '开发者'],
    pricing: 'freemium',
    useCases: ['自建自动化', 'API 编排', '数据同步', 'DevOps', '企业流程'],
    prosCons: { pros: ['开源免费', '自托管', '隐私可控', '400+ 节点', '可扩展'], cons: ['需技术配置', '云服务收费', 'UI 略复杂', '性能瓶颈', '社区支持'] },
    officialUrl: 'https://n8n.io',
    score: 8.6,
  },
  {
    id: 'bolt-new',
    name: 'Bolt.new',
    description: 'AI 全栈 Web 应用生成器。输入描述生成可运行的完整 Web 应用。',
    shortDesc: 'AI 全栈 Web 应用生成',
    url: 'https://bolt.new',
    category: 'code',
    tags: ['全栈', 'Web 应用', '代码生成', 'AI 开发', '快速原型'],
    pricing: 'freemium',
    useCases: ['快速原型', 'Web 应用', 'MVP 开发', '全栈项目', '学习'],
    prosCons: { pros: ['一键生成', '全栈输出', '可运行', '迭代修改', '快速原型'], cons: ['复杂项目弱', '免费限制', '代码质量', '定制困难', '依赖平台'] },
    officialUrl: 'https://bolt.new',
    score: 8.5,
  },
  {
    id: 'v0',
    name: 'V0 by Vercel',
    description: 'Vercel AI 前端生成工具。文本描述生成 React 组件和页面。支持 Tailwind。',
    shortDesc: 'Vercel AI 前端组件生成',
    url: 'https://v0.dev',
    category: 'code',
    tags: ['前端', 'React', 'Vercel', 'UI 生成', 'Tailwind'],
    pricing: 'freemium',
    useCases: ['UI 组件', '页面生成', '设计原型', '前端开发', '快速迭代'],
    prosCons: { pros: ['质量高', 'Tailwind 原生', 'Vercel 集成', '迭代方便', '组件级'], cons: ['免费限制', '仅前端', 'Vercel 绑定', '复杂逻辑弱', '依赖文本描述'] },
    officialUrl: 'https://v0.dev',
    score: 8.6,
  },
  {
    id: 'lovable',
    name: 'Lovable',
    description: 'AI 应用构建平台用自然语言描述生成前端应用。支持 React Vue。',
    shortDesc: 'AI 前端应用构建平台',
    url: 'https://lovable.dev',
    category: 'code',
    tags: ['AI 开发', '前端', '应用生成', 'React', '自然语言'],
    pricing: 'freemium',
    useCases: ['前端开发', 'UI 设计', '应用原型', 'MVP 构建', '学习'],
    prosCons: { pros: ['自然语言', '快速生成', 'React 输出', '迭代方便', '可视化'], cons: ['免费限制', '后端弱', '代码可维护性', '复杂 UI 弱', '新平台'] },
    officialUrl: 'https://lovable.dev',
    score: 8.3,
  },
  {
    id: 'pika',
    name: 'Pika',
    description: 'AI 视频生成工具文生视频图生视频。界面简洁易用创作者友好。',
    shortDesc: '用户友好的 AI 视频生成工具',
    url: 'https://pika.art',
    category: 'video',
    tags: ['AI 视频', '视频生成', '短视频', '创作者', '风格化'],
    pricing: 'freemium',
    useCases: ['短视频创作', '动画制作', '社媒视频', '广告素材', '艺术实验'],
    prosCons: { pros: ['操作简单', '免费可用', '风格丰富', '生成快速', '社区活跃'], cons: ['分辨率低', '一致性差', '免费有水印', '付费贵', '长视频弱'] },
    officialUrl: 'https://pika.art',
    score: 8.5,
  },
  {
    id: 'invideo-ai',
    name: 'InVideo AI',
    description: 'AI 视频生成平台文本输入生成完整视频。5000+ 模板 AI 脚本编写。',
    shortDesc: '文本转视频 AI 生成平台',
    url: 'https://invideo.io',
    category: 'video',
    tags: ['AI 视频', '文本转视频', '视频模板', '内容创作', '营销视频'],
    pricing: 'freemium',
    useCases: ['营销视频', 'YouTube 内容', '社媒广告', '产品演示', '解说视频'],
    prosCons: { pros: ['文本转视频', '海量模板', '自动配音', '新手友好', '快速制作'], cons: ['免费水印', '定制化有限', 'AI 场景普通', '高级版贵', '配音质量不一'] },
    officialUrl: 'https://invideo.io',
    score: 8.6,
  },
  {
    id: 'hypotenuse',
    name: 'Hypotenuse AI',
    description: 'AI 内容写作平台专注 SEO 研究。生成优化文章和广告文案。',
    shortDesc: 'AI SEO 内容写作平台',
    url: 'https://www.hypotenuse.ai',
    category: 'writing',
    tags: ['内容写作', 'SEO', '文章生成', '产品描述', '营销文案'],
    pricing: 'paid',
    useCases: ['SEO 文章', '产品描述', '广告文案', '社媒内容', '邮件营销'],
    prosCons: { pros: ['SEO 优化', '内容连贯', '多模板', '批量生成', '易用性强'], cons: ['价格较高', '无免费版', '英文为主', '需人工编辑', '中文差'] },
    officialUrl: 'https://www.hypotenuse.ai',
    score: 8.2,
  },
  {
    id: 'gemini',
    name: 'Google Gemini',
    description: 'Google 多模态 AI 模型理解文本图像音频视频和代码。集成 Google 生态。',
    shortDesc: 'Google 多模态 AI 模型',
    url: 'https://gemini.google.com',
    category: 'search',
    tags: ['AI 对话', '多模态', 'Google', '长上下文', '搜索'],
    pricing: 'freemium',
    useCases: ['多模态理解', '研究分析', '内容创作', '编程辅助', '信息检索'],
    prosCons: { pros: ['多模态强', '超长上下文', 'Google 集成', '免费可用', '知识更新'], cons: ['中文有时差', '创意不足', '回答较保守', '生态系统限制', '高级版贵'] },
    officialUrl: 'https://gemini.google.com',
    score: 9.1,
  },
  {
    id: 'grok',
    name: 'xAI Grok',
    description: 'xAI 开发的 AI 助手实时连接 X（Twitter）数据。回答问题分析新闻。',
    shortDesc: 'xAI 实时 AI 助手',
    url: 'https://grok.com',
    category: 'search',
    tags: ['AI 对话', '实时数据', 'X/Twitter', 'xAI', '新闻分析'],
    pricing: 'freemium',
    useCases: ['新闻分析', '社媒洞察', '实时问答', '内容生成', '趋势追踪'],
    prosCons: { pros: ['实时数据接入', '幽默风格', 'X 集成', '新闻分析', '快速响应'], cons: ['X Premium 需付费', '非 X 场景弱', '开发中', '功能有限', '准确度待提升'] },
    officialUrl: 'https://grok.com',
    score: 8.5,
  },
  {
    id: 'klap',
    name: 'Klap',
    description: 'AI 短视频剪辑工具从长视频提取精彩片段。动态字幕和特效适配。',
    shortDesc: 'AI 短视频剪辑与动态字幕',
    url: 'https://klap.app',
    category: 'video',
    tags: ['视频剪辑', '短视频', '字幕 AI', '播客工具', '创作者'],
    pricing: 'freemium',
    useCases: ['播客剪辑', '教育短视频', 'YouTube 转 Shorts', '社媒内容', '访谈高光'],
    prosCons: { pros: ['高光检测', '动态字幕', '格式优化', '易用性强', '效率高'], cons: ['免费限制', '选择不完美', '无完整编辑', '专业版贵', '较新平台'] },
    officialUrl: 'https://klap.app',
    score: 8.4,
  },
  {
    id: 'pictory',
    name: 'Pictory AI',
    description: 'AI 视频创作者长内容转品牌短视频。从文章脚本提取高光自动剪辑。',
    shortDesc: 'AI 长内容转品牌短视频',
    url: 'https://pictory.ai',
    category: 'video',
    tags: ['视频创作', '内容再创作', '自动编辑', '品牌视频', '创作者'],
    pricing: 'freemium',
    useCases: ['文章转视频', '长视频摘要', '社媒剪辑', '品牌内容', '博客转视频'],
    prosCons: { pros: ['文章转视频', '自动故事板', '文本编辑', '品牌模板', '高效'], cons: ['免费水印', '配音机械', '定制有限', '月度额度', '复杂剪辑弱'] },
    officialUrl: 'https://pictory.ai',
    score: 8.5,
  },
  {
    id: 'reclaim',
    name: 'Reclaim AI',
    description: 'AI 日历调度工具自动保护专注时间。灵活调度会议和习惯任务。',
    shortDesc: 'AI 日历调度与时间保护',
    url: 'https://reclaim.ai',
    category: 'productivity',
    tags: ['日历 AI', '调度', '时间管理', '谷歌日历', '效率'],
    pricing: 'freemium',
    useCases: ['日程管理', '专注时间', '会议调度', '习惯养成', '平衡工作'],
    prosCons: { pros: ['自动调度', '专注保护', '习惯跟踪', '灵活调整', 'Google 集成'], cons: ['免费限制', 'Google 绑定', '高级版贵', '学习曲线', '偶尔不准'] },
    officialUrl: 'https://reclaim.ai',
    score: 8.4,
  },
  {
    id: 'krisp',
    name: 'Krisp AI',
    description: 'AI 降噪工具让通话更清晰。消除背景噪音回声支持所有通讯应用。',
    shortDesc: 'AI 通话降噪工具',
    url: 'https://krisp.ai',
    category: 'productivity',
    tags: ['降噪', '通话质量', '音频 AI', '远程办公', '效率'],
    pricing: 'freemium',
    useCases: ['远程会议', '通话降噪', '录音清理', '播客录制', '在线教学'],
    prosCons: { pros: ['降噪优秀', '实时处理', '应用无关', '回声消除', '背景净化'], cons: ['免费时间限制', '偶尔误消人声', '资源消耗', '无录音功能', '高级版贵'] },
    officialUrl: 'https://krisp.ai',
    score: 8.6,
  },
];

// Update category counts
const catCounts: Record<string, number> = {};
for (const t of tools) {
  catCounts[t.category] = (catCounts[t.category] || 0) + 1;
}
for (const cat of categories) {
  cat.count = catCounts[cat.id] || 0;
}

// === Phase 2: SEO & Affiliate Helpers ===

export function outboundLink(url: string, label: string, trackingId?: string): { href: string; rel: string; target: string } {
  const href = trackingId ? `${url}?ref=stykai&aid=${trackingId}` : `${url}?ref=stykai`;
  return { href, rel: 'noopener noreferrer nofollow', target: '_blank' };
}

export function getCategoryName(catId: string): string {
  const cat = categories.find(c => c.id === catId);
  return cat ? cat.name : catId;
}

export function getCategoryIcon(catId: string): string {
  const cat = categories.find(c => c.id === catId);
  return cat ? cat.icon : '';
}

export function getToolsByCategory(catId: string): Tool[] {
  return tools.filter(t => t.category === catId).sort((a, b) => (b.score || 0) - (a.score || 0));
}

export function getToolsByTag(tag: string): Tool[] {
  return tools.filter(t => t.tags.some(tg => tg.includes(tag))).sort((a, b) => (b.score || 0) - (a.score || 0));
}

export function getRelatedTools(tool: Tool, limit: number = 4): Tool[] {
  const sameCat = tools.filter(t => t.id !== tool.id && t.category === tool.category);
  const sameTag = tools.filter(t => t.id !== tool.id && t.category !== tool.category && t.tags.some(tg => tool.tags.includes(tg)));
  const others = tools.filter(t => t.id !== tool.id && t.category !== tool.category && !t.tags.some(tg => tool.tags.includes(tg)));
  const combined = [...sameCat, ...sameTag, ...others];
  return combined.slice(0, limit);
}

export function getAlternatives(tool: Tool, limit: number = 3): Tool[] {
  return tools.filter(t => t.id !== tool.id && t.category === tool.category).sort((a, b) => (b.score || 0) - (a.score || 0)).slice(0, limit);
}

export function getPricingLabel(pricing: string): string {
  const map: Record<string, string> = { free: '免费', freemium: '免费+付费', paid: '付费' };
  return map[pricing] || pricing;
}

export function generateFAQs(tool: Tool): { q: string; a: string }[] {
  const faqs = [
    { q: `${tool.name} 是什么？`, a: `${tool.description}` },
    { q: `${tool.name} 收费吗？`, a: `${tool.name} 采用 ${getPricingLabel(tool.pricing)} 模式。${tool.pricing === 'free' ? '完全免费使用。' : tool.pricing === 'freemium' ? '提供免费版本，付费版本有更多功能和额度。' : '需要付费订阅才能使用全部功能。'}` },
    { q: `${tool.name} 有哪些主要功能？`, a: `${tool.name} 的核心功能包括：${tool.tags.join('、')}。主要应用于 ${tool.useCases.join('、')} 等场景。` },
    { q: `${tool.name} 适合哪些人使用？`, a: `${tool.name} 适合需要 ${tool.useCases.slice(0, 3).join('、')} 的用户。${tool.prosCons.pros.slice(0, 2).join('和')} 是其突出优势。` },
    { q: `${tool.name} 有什么优缺点？`, a: `优点包括：${tool.prosCons.pros.join('、')}。不足之处：${tool.prosCons.cons.join('、')}。总体评分 ${tool.score}/10。` },
  ];
  return faqs;
}

export function slugify(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

// SEO page descriptions
export function getSeoPageData() {
  return {
    'best-ai-tools': {
      title: '2025年最好用的 AI 工具推荐 Top 82+ | 精选评测排行',
      description: '精选 82+ 款最好用的 AI 工具，涵盖写作、图像、编程、视频等 8 大分类。真实评分、优缺点分析，帮你找到最适合的 AI 工具。',
      h1: '2025年最好用的 AI 工具推荐',
      intro: 'AI 工具爆发式增长的时代，我们从 82+ 款工具中精选出各分类最值得使用的产品。以下是按分类整理的最佳 AI 工具推荐。',
    },
    'ai-writing-tools': {
      title: 'AI 写作工具推荐 Top 10 | 2025年最好用的 AI 写作助手',
      description: '精选 10+ 款 AI 写作工具，对比 ChatGPT、Claude、Grammarly、Notion AI 等。从功能、定价、优缺点全面评测。',
      h1: 'AI 写作工具推荐',
      intro: 'AI 写作工具可以帮助你更高效地创作内容、优化文案、改进语法。以下是精选的 AI 写作工具，按评分排序。',
    },
    'ai-tools-for-students': {
      title: '适合学生的 AI 工具推荐 | 学习效率提升必备',
      description: '学生必备的 AI 工具推荐，涵盖写作辅助、研究搜索、编程学习、笔记管理等场景，帮助提升学习效率。',
      h1: '学生必看的 AI 工具推荐',
      intro: '作为学生，AI 工具可以帮你写论文、做研究、学编程、管理笔记。以下是专为学生精选的 AI 工具。',
    },
    'ai-tools-for-business': {
      title: '企业级 AI 工具推荐 | 提升业务效率的 AI 解决方案',
      description: '为企业团队精选的 AI 工具，涵盖营销、生产力、数据分析、内容创作等场景。提升团队效率，驱动业务增长。',
      h1: '企业级 AI 工具推荐',
      intro: '企业团队可以使用 AI 工具提高生产力、优化营销、自动化工作流。以下是适合企业的 AI 工具推荐。',
    },
    'chatgpt-alternatives': {
      title: 'ChatGPT 替代方案 | 2025年最佳替代工具推荐',
      description: '寻找 ChatGPT 替代品？我们精选了 Claude、DeepSeek、Gemini 等 10+ 款替代工具，从功能、定价、优缺点全面对比。',
      h1: 'ChatGPT 替代工具推荐',
      intro: 'ChatGPT 虽然强大，但还有其他优秀的 AI 对话工具值得尝试。以下是不错的 ChatGPT 替代方案。',
    },
    'midjourney-alternatives': {
      title: 'Midjourney 替代方案 | 2025年最佳 AI 图像生成工具推荐',
      description: '寻找 Midjourney 替代品？对比 DALL-E 3、Stable Diffusion、Leonardo、Canva AI 等图像生成工具，找到最适合你的选择。',
      h1: 'Midjourney 替代工具推荐',
      intro: 'Midjourney 虽好，但其他 AI 图像生成工具也有独特的优势。以下是值得关注的 Midjourney 替代方案。',
    },
    'notion-ai-alternatives': {
      title: 'Notion AI 替代方案 | 2025年最佳 AI 笔记知识管理工具',
      description: '寻找 Notion AI 替代品？对比 Mem.ai、Taskade、Obsidian 等 AI 知识管理工具，找到更适合你的笔记方案。',
      h1: 'Notion AI 替代工具推荐',
      intro: 'Notion AI 虽然集成方便，但其他 AI 笔记和知识管理工具也各具特色。以下是值得尝试的替代方案。',
    },
    'chatgpt-vs-claude': {
      title: 'ChatGPT vs Claude 详细对比 | 哪个更适合你？',
      description: 'ChatGPT 和 Claude 全面对比：功能、定价、优缺点、使用场景。帮你决定哪个 AI 助手最适合你的需求。',
      h1: 'ChatGPT vs Claude：详细对比评测',
      intro: 'ChatGPT 和 Claude 是当前最受欢迎的两款 AI 对话助手。它们各有特色，适合不同的使用场景。以下是详细对比。',
    },
    'midjourney-vs-dalle': {
      title: 'Midjourney vs DALL-E 3 详细对比 | AI 图像生成工具怎么选？',
      description: 'Midjourney 和 DALL-E 3 全面对比：图像质量、文字渲染、定价、使用体验。帮你选择最适合的 AI 图像生成工具。',
      h1: 'Midjourney vs DALL-E 3：详细对比评测',
      intro: 'Midjourney 和 DALL-E 3 是 AI 图像生成领域的两大标杆。它们风格不同，各有擅长领域。以下是详细对比。',
    },
  };
}

export function getBestForData() {
  return {
    'content-creation': { title: '内容创作最佳 AI 工具', desc: '适合内容创作者的最佳 AI 工具，涵盖写作、图像、视频生成等。', tag: '内容创作' },
    'programming': { title: '编程开发最佳 AI 工具', desc: '专为开发者设计的最佳 AI 编程工具，提升代码效率。', tag: '编程' },
    'design': { title: '设计创意最佳 AI 工具', desc: '设计师和创意工作者必备的 AI 工具推荐。', tag: '设计' },
    'marketing': { title: '营销推广最佳 AI 工具', desc: '营销团队的最佳 AI 工具，提升转化和效率。', tag: '营销' },
    'education': { title: '学习教育最佳 AI 工具', desc: '学生和教育工作者必看的 AI 工具，提升学习效率。', tag: '教育' },
    'research': { title: '学术研究最佳 AI 工具', desc: '学术研究人员的最佳 AI 工具，加速文献综述和研究发现。', tag: '研究' },
  };
}
